// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMYLKeht6Z6paswuvYJ9pj6Gn65juMcHI',
    appId: '1:952337608773:web:7c7fecba7495d1c708f32c',
    messagingSenderId: '952337608773',
    projectId: 'mrapp-b8d1e',
    authDomain: 'mrapp-b8d1e.firebaseapp.com',
    databaseURL: 'https://mrapp-b8d1e-default-rtdb.firebaseio.com',
    storageBucket: 'mrapp-b8d1e.appspot.com',
    measurementId: 'G-R7MCKPRSN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV1tYrjT9q5DMDyX6we1Z67t_PBLHEatw',
    appId: '1:952337608773:android:65fda7db4d6c1cc008f32c',
    messagingSenderId: '952337608773',
    projectId: 'mrapp-b8d1e',
    databaseURL: 'https://mrapp-b8d1e-default-rtdb.firebaseio.com',
    storageBucket: 'mrapp-b8d1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXPdl5FYZXvpRcj3ecnHy9vq2QbGkfojk',
    appId: '1:952337608773:ios:e11b10610ec6322c08f32c',
    messagingSenderId: '952337608773',
    projectId: 'mrapp-b8d1e',
    databaseURL: 'https://mrapp-b8d1e-default-rtdb.firebaseio.com',
    storageBucket: 'mrapp-b8d1e.appspot.com',
    androidClientId: '952337608773-0ahdnujqhgsqf5kv7st54kb55eu5l36m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXPdl5FYZXvpRcj3ecnHy9vq2QbGkfojk',
    appId: '1:952337608773:ios:e11b10610ec6322c08f32c',
    messagingSenderId: '952337608773',
    projectId: 'mrapp-b8d1e',
    databaseURL: 'https://mrapp-b8d1e-default-rtdb.firebaseio.com',
    storageBucket: 'mrapp-b8d1e.appspot.com',
    androidClientId: '952337608773-0ahdnujqhgsqf5kv7st54kb55eu5l36m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMYLKeht6Z6paswuvYJ9pj6Gn65juMcHI',
    appId: '1:952337608773:web:e9b8d4b64bceba9508f32c',
    messagingSenderId: '952337608773',
    projectId: 'mrapp-b8d1e',
    authDomain: 'mrapp-b8d1e.firebaseapp.com',
    databaseURL: 'https://mrapp-b8d1e-default-rtdb.firebaseio.com',
    storageBucket: 'mrapp-b8d1e.appspot.com',
    measurementId: 'G-1FXBQJHER6',
  );
}
